# Generated by Django 4.0 on 2023-01-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_date',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
