# Generated by Django 4.0 on 2023-01-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_orders_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='expected_date',
        ),
    ]
